### ISSUE TITLE
親ブロックのスタイルが子ブロックに継承される

### ISSUE THREAD

**Issue by xs-khosomi** [xserver-inc/cocoon#157]
InnerBlocksを設定しているブロックの内包ブロックに親ブロックのスタイルが継承される
<img width="426" alt="capture01" src="https://github.com/xserver-inc/cocoon/assets/132876957/7ed6f37e-bcfc-42be-b849-af08bbb3ce0e">
<img width="622" alt="capture02" src="https://github.com/xserver-inc/cocoon/assets/132876957/c6aa81d4-edb5-43fe-a3a9-4012cb9bda83">

**Comment by xs-khosomi** [comment]
## 対象ブロック

- [ ] アコーディオン
- [ ] FAQ
- [ ] タイムライン
- [ ] タブ見出しボックス
- [ ] ラベルボックス
- [ ] 吹き出し
- [ ] 見出しボックス

**Comment by yhira** [comment]
ご連絡ありがとうございます。
とりあえず手元で修正用のブランチを切って1つずつ修正していければと思っております。
アコーディオンブロックはこんな感じで修正できたかと思います。
<img width="731" alt="2023-11-12_09h20_07" src="https://github.com/xserver-inc/cocoon/assets/1787429/7eef656d-c2ee-4fc2-81ca-a9c6539d98e1">

他のブロックも修正した後masterブランチにマージしようと思います。
