### ISSUE TITLE
シェアボタンのオプションに分散型SNSを追加する

### ISSUE THREAD

**Issue by kakkokari-gtyih** [xserver-inc/cocoon#166]
Twitter (X) のもろもろで分散型SNSが注目されているので、それら向けのシェアボタンを追加したいです
分散型SNSには以下のようなものがあります。

- Mastodon
- Misskey

分散型SNSはサーバーが複数存在するため、シェアしたいサーバーのURLを入力してもらうUIが必要になりますが、[Misskeyは公式でシェアボタン中継機能が実装された](https://misskey-hub-next.vercel.app/ja/tools/share-link-generator/)ため、比較的容易に実装が可能かと思います。
Mastodonではそのようなサービスはサードパーティーでしか提供されていないので悩みどころですが…

（余談：XServerさんはMisskeyのスポンサーになっていただいています）

**Comment by yhira** [comment]
Misskeyなんてのもあるんですね。
検討させていただきます。

**Comment by yhira** [comment]
テキストメインでも結構減っちゃうもんだね。。

**Comment by kakkokari-gtyih** [comment]
> 本実装の際は[こちら](https://misskey-hub.net/appendix/assets.html#%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3)で配布されいる公式のアイコンを使用することになると思います。

SVGはこちらのやつを使うのがいいと思います🙏
https://github.com/misskey-dev/misskey-hub-next/blob/master/assets/svg/misskey_mi_bi.svg

**Comment by yhira** [comment]
> 処理の流れは

この処理自体はJavaScriptで行っていますが、別にPHPで処理を行っても良いのですよね？

**Comment by kakkokari-gtyih** [comment]
> > 処理の流れは
> 
> この処理自体はJavaScriptで行っていますが、別にPHPで処理を行っても良いのですよね？

Misskeyは同じ形式のURLに飛べれば大丈夫です
マストドンはサーバーを選択させるUIを設ける必要がありそうですが…

**Comment by MizuiMiduki** [comment]
かっこかり氏が言われているように、決まった形式のURLを生成して設定できれば、PHPでもJavaScriptでもPythonでも何でも大丈夫です

**Comment by yhira** [comment]
年末に体調を崩してひと月ほど入院しておりました。
その間たまった仕事などをこなしていたりして返信が遅くなり申し訳ありません。
GitHubのファイルの方にMastodonとMisskeyのシェアボタンを追加しておきました。
https://github.com/xserver-inc/cocoon

<img width="623" alt="2024-02-11_20h16_45" src="https://github.com/xserver-inc/cocoon/assets/1787429/fddcba1e-415f-436c-800f-e024fe64244d">

**Comment by kakkokari-gtyih** [comment]
確認しました。大変な時期にわざわざありがとうございました🙏🏻´-

**Comment by MizuiMiduki** [comment]
対応ありがとうございます!
早速、現時点で最新のものをダウンロードして使用してみたところ、プロフィール設定内にあるアカウントURLの入力フォームの『Misskey』が『Misskfy』になっている誤植を発見しました。

![Screenshot_20240212-100013_Chrome.jpg](https://github.com/xserver-inc/cocoon/assets/105696149/a9d9eeea-09da-412c-ab72-fcf6f5ff9938)

他のところでは今のところ誤植を見つけてはいませんが、また不具合等あればご報告させていただきます

**Comment by MizuiMiduki** [comment]
#177 
誤植を修正したものをpull requestしておきました。ご確認ください

**Comment by yhira** [comment]
ご確認いただきありがとうございます。
またプルリクもありがとうございます！
もう一度誤字がないか確認してプルリクをマージさせていただこうと思います。

**Comment by yhira** [comment]
ボタンの動作的には今回の実装のもので問題なかったでしょうか？

**Comment by MizuiMiduki** [comment]
Mastodon、Misskeyともに、シェアボタンとフォローボタンが問題なく動いています。あれから誤植など更に探しましたが、コメントアウトも含め問題なかったです

**Comment by yhira** [comment]
ご確認いただきありがとうございます。
僕も今回の実装でアカウントだけは作って試しましたが、普段使われている方に問題なかったと言っていただけて安心いたしました。
