### ISSUE TITLE
カルーセルに表示する画像サイズがバラバラなときに、タイトルがズレて表示されてしまうのを解消してほしい

### ISSUE THREAD

**Issue by MizuiMiduki** [xserver-inc/cocoon#178]
画像サイズ・アスペクト比がバラバラなときに、タイトルの表示位置が画像のようにズレてしまいます。
(画像は他が16:9にも関わらず、これのみ違うアスペクト比の画像を使用しています)
![スクリーンショット 2024-02-13 010543](https://github.com/xserver-inc/cocoon/assets/105696149/2bb16a3f-17f0-49e0-92b9-1ba14ec590d8)

私の環境ではテーマのCSSに下記を追記して、16:9に変換して表示することで対応しています。
```
.carousel-entry-card-thumb img{
	aspect-ratio: 16 / 9;
	object-fit: contain;
}
```
![スクリーンショット 2024-02-13 013843](https://github.com/xserver-inc/cocoon/assets/105696149/04a01ed1-20a4-436c-add5-332524b8f957)

Pull Requestを送ろうかと思いましたが、設定で他のアスペクト比に設定している場合のPHP処理が分からなかったので、お願いしたいです

**Comment by MizuiMiduki** [comment]
追記

また、私の環境ではアイキャッチやカードの画像サイズが大きかったり、アスペクト比が違ったりしても視認性が下がらないように、同じように

```
.eye-catch img,
.card-thumb img{
	aspect-ratio: 16 / 9;
	object-fit: contain;
}
```
と記述して16:9にしています。

**Comment by yhira** [comment]
Regenerate Thumbnailsとかは使われていない感じでしょうか？
https://wp-cocoon.com/regenerate-thumbnails/
Cocoonの場合は、Regenerate Thumbnailsと連携してその場所に適したサムネイルサイズになるような仕様にしていました。

とはいえRegenerate Thumbnailsを使用しなければサムネイルの高さがガタガタになるのはその通りなんです。前々からやりたいと思っていて放置しておりました。
なのでaspect-ratioを使用して全てのCocoon設定のアスペクト比に全てのサムネイルを対応させようと思います。
<img width="571" alt="2024-02-15_19h46_13" src="https://github.com/xserver-inc/cocoon/assets/1787429/71b725e6-1ca9-43f0-be57-a83e85a767d4">


そしてゆくゆくは無駄に生成されるサムネイルも全て元画像1つにしたいと思います。
https://github.com/xserver-inc/cocoon/blob/4b0644a641ba3859bc54b8d8623f382d1ece6c96/lib/settings.php#L23-L69
※以前は読み込みサイズの影響から再生数を必須としていましたが、WordPressデフォルトで画像に対してLazy loadが実装されたことから画像サイズが大きい元画像でも良いのかなと（add_image_sizeもサムネイルを全て削除しないまでももう少し数を減らそうと思っています）。

**Comment by MizuiMiduki** [comment]
以前はRegenerate Thumbnailsで再生成をしていたのですが、
- 少しとはいえ再生成中にサイト公開以外にリソースを使うとその間の表示速度が低下するのではという懸念
- インストールするプラグインは最低限にしておきたい
というので、最近はaspect-ratioで16:9にして表示しています。

なので、テーマ側で標準対応していただけると、非常にありがたいです。

**Comment by yhira** [comment]
Regenerate Thumbnailsを使用していないんですね。
それならそういった状態になる理由も分かりました。

> 少しとはいえ再生成中にサイト公開以外にリソースを使うとその間の表示速度が低下するのではという懸念

全ての画像をまとめて再生成でもしていない限り、再生成にリソースを使うのは画像をアップロードしている時だけになるので、1日にすごい頻度で画像アップロードするなんてケース以外は個人的には大丈夫とは思います（PVが多すぎるとかサーバーが貧弱すぎて処理が追いついていないなんて場合以外）。

> なので、テーマ側で標準対応していただけると、非常にありがたいです

アスペクト比のCSSを実装したものをアップしておきました。
https://github.com/xserver-inc/cocoon/commit/b83901f40d6887ba7f88576906978c391fdf5be6

**Comment by MizuiMiduki** [comment]
アスペクト比のCSSが入ったもの、確認しました。
プラグイン無しでもサムネイルのバランスが良く見やすくなり、とても良かったです

**Comment by yhira** [comment]
ご確認いただきありがとうございます。
