### ISSUE TITLE
コミット 3d087f50fbe9c6e839dc6443860cd67d5ba02a2f 以降、Google フォント使用時に Regular ウェイトしか読み込まなくなっている問題を修正してほしい

### ISSUE THREAD

**Issue by tsukumijima** [xserver-inc/cocoon#219]
@yhira 表題の通りです。

原因は明確で、https://github.com/xserver-inc/cocoon/commit/3d087f50fbe9c6e839dc6443860cd67d5ba02a2f での Noto Sans KR などの韓国語フォントのサポート追加により、`https://fonts.googleapis.com/css` **(`https://fonts.googleapis.com/css2` ではないことに注意)** への URL クエリが、バリアブルフォント (ウェイトを動的に変えられ、フォントサイズが大幅に小さくなる) 用の表記に変更されたからです。

<img width="1579" alt="image" src="https://github.com/user-attachments/assets/052af3f4-c9bb-43bb-9dd7-d556f21cdedb"><br>

現在 Google Fonts にて Noto Sans JP (バリアブルフォント版) の埋め込みコードを取得すると、画像のように CSS API URL として `https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap` が生成されます。

しかしながら、https://github.com/xserver-inc/cocoon/commit/3d087f50fbe9c6e839dc6443860cd67d5ba02a2f でのバリアブルフォント対応後も、https://github.com/xserver-inc/cocoon/blob/master/lib/utils.php#L1806 が `https://fonts.googleapis.com/css` になっているために、**現在最新版の Cocoon では Noto Sans JP のロード用 CSS として `https://fonts.googleapis.com/css?family=Noto+Sans+JP:wght@100..900` が読み込まれています。**

そして https://fonts.googleapis.com/css?family=Noto+Sans+JP:wght@100..900 からは (アクセスすれば分かる通り) `font-weight: 400;` の Web フォントしか返って来ないために、**現在最新版の Cocoon では、Noto Sans JP や Noto Serif JP などの Regular 以外のウェイトがサイト上に表示されない状態になってしまっています。**

https://developers.google.com/fonts/docs/css2 にある通り `https://fonts.googleapis.com/css` は互換性のために残されているに過ぎず、特にバリアブルフォントのような新しい機能、新しい URL クエリには対応していません。
`https://fonts.googleapis.com/css` は従来形式の URL クエリしか受け付けないものと思われます。

> [!NOTE]
> 正確には font-weight での細かい指定が機能せずほとんど Regular ウェイトで表示され、font-weight: 700 以上のウェイトでは Regular ウェイトをソフトウェア的に無理やり Bold 化した状態で表示されています。
> この「なんちゃって Bold 状態」は画数の多い漢字が潰れる・文字があまり太くならず Regular との差があまりない・せっかくの美しいフォントが汚くなるなど多くの問題があり、とても実用的ではありません。

私のサイトもこの意図しないデグレードにより一部のサイトデザインが崩れているため、早急に修正していただきたいです。
修正といっても、やるべきことは `https://fonts.googleapis.com/css`を `https://fonts.googleapis.com/css2` に変更することだけです。

今更敢えて `https://fonts.googleapis.com/css` を使わなければならない特段の事情がない限り、Cocoon 内の他のコードも含め、この機会に `https://fonts.googleapis.com/css2` CSS API URL への移行をお勧めします。

よろしくお願いいたします。

**Comment by yhira** [comment]
ご指摘いただきありがとうございます。
Googleフォントの呼び出し元がいつの間にか css → css2 に変更されているのに気づいておらずそのまま使っていました。
取り急ぎGoogleフォントの呼び出し元を修正させていただきました。
https://github.com/xserver-inc/cocoon/commit/3b66a808bd765e919e2ceaf96492b0653a12c596

**Comment by tsukumijima** [comment]
@yhira 早急な修正ありがとうございます！
新バージョンリリース後、再び Regular 以外のフォントが問題なく表示されるようになったことを確認次第、この Issue はクローズさせていただきます。

**Comment by tsukumijima** [comment]
@yhira 無事 Cocoon 2.7.7.3 にて Noto Sans JP の Bold ウェイトが正しく表示されるようになっていることを確認しました！
迅速な修正ありがとうございました🙏

**Comment by yhira** [comment]
ご確認いただきありがとうございます！
