### ISSUE TITLE
タグ名の最後の文字が半角閉じ括弧 ")" の場合、その半角閉じ括弧 ")" が表示されない

### ISSUE THREAD

**Issue by inzeilife** [xserver-inc/cocoon#248]
まず初めに、素晴らしいWPテーマを公開してくださり、ありがとうございます。 :bow:

## 事象

さて本題ですが、タイトルの通り、タグの最後の文字が半角閉じ括弧 ")" の場合に表示されない、出力されないという事象となります。

![image](https://github.com/user-attachments/assets/a42eccda-7724-4b32-b518-854696653a09)

![image](https://github.com/user-attachments/assets/1d29bc71-1112-4595-876f-455aadadee86)

![image](https://github.com/user-attachments/assets/a802c171-4103-4977-90fc-a3430a50a4f4)

## 予想される原因

以下の90行目の処理が、本来は`<span class="tag-link-count">`の方の閉じタグ`) </span>`のみに適用されるべきところ、タグ名が ")" で終わっていることにより、`<span class="tag-caption">`の方の閉じタグ`) </span>`にも適用されてしまっているように見受けられました。

https://github.com/xserver-inc/cocoon/blob/fc4408435e0bffa9ac94aa09d2cc392e7f504e15/lib/widget.php#L90

## 環境

- WordPress: 6.7.1
- Cocoon: 2.8.3

**Comment by inzeilife** [comment]
すばやい対応ありがとうございます！

上記の修正で閉じ括弧 ")" が表示されることを確認できたので、本issueはcloseさせていただきます。

![image](https://github.com/user-attachments/assets/a8b48d54-3b18-4d7e-a245-fd5459f170d5)

**Comment by yhira** [comment]
ご確認いただきありがとうございます！
