### ISSUE TITLE
言語が中国語をサポートできることを願っています

### ISSUE THREAD

**Issue by OFZFZS** [xserver-inc/cocoon#38]
私は中国のユーザーです。このテーマがとても好きで、中国語をサポートしたいと思っています

**Comment by yhira** [comment]
こんにちは。ありがとうございます。
それは、中国語の言語ファイルを作っていただけるということでしょうか？

**Comment by OFZFZS** [comment]
> こんにちは。ありがとうございます。
> それは、中国語の言語ファイルを作っていただけるということでしょうか？

はい、ありがとうございます。簡体字中国語と繁体字中国語を支持してほしいです。

**Comment by yhira** [comment]
「支持して欲しい」とはどういうことでしょう？
一般的に日本語で指示とは支持とは「ささえること。もちこたえること。」を指します。
「作って欲しい」ということでしょうか。

**Comment by OFZFZS** [comment]
1
