### ISSUE TITLE
テーマアップデート時にサイトが壊れる

### ISSUE THREAD

**Issue by 1008k** [xserver-inc/cocoon#74]
お世話になっております。

テーマのアップデート時にサイトが壊れてしまう現象が発生しています。
WordPressのバージョンは6.0.3、PHPのバージョンは8.1.6です。

ログは以下です。
`Fatal error: Uncaught Error: Attempt to modify property "response" on bool in /home/public_html/wp-content/themes/cocoon-master/lib/theme-update-checker.php:182 Stack trace: #0 /home/public_html/wp-includes/class-wp-hook.php(309): ThemeUpdateChecker->injectUpdate(false) #1 /home/public_html/wp-includes/plugin.php(191): WP_Hook->apply_filters(false, Array) #2 /home/public_html/wp-includes/option.php(1960): apply_filters('site_transient_...', false, 'update_themes') #3 /home/public_html/wp-includes/update.php(787): get_site_transient('update_themes') #4 /home/public_html/wp-admin/menu.php(33): wp_get_update_data() #5 /home/public_html/wp-admin/admin.php(158): require('/home/...') #6 /home/public_html/wp-admin/index.php(10): require_once('/home/...') #7 {main} thrown in /home/public_html/wp-content/themes/cocoon-master/lib/theme-update-checker.php on line 182`

私のケースではログで指摘されている行をコメントアウトしたところ復旧しました。

以下でも同様の事象が報告されているようでした。
https://ja.wordpress.org/support/topic/%E3%81%93%E3%81%AE%E3%82%B5%E3%82%A4%E3%83%88%E3%81%A7%E9%87%8D%E5%A4%A7%E3%81%AA%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%8C%E7%99%BA%E7%94%9F%E3%81%97%E3%81%BE%E3%81%97%E3%81%9F%E3%80%82-2/

テーマのアップデートに使用されているライブラリのサイトを見てみたところ「このライブラリは廃止されました」といった事が書かれているので、PHPの新しめのバージョンに対応できてないのかもしれません。
https://w-shadow.com/blog/2011/06/02/automatic-updates-for-commercial-themes/comment-page-8/

ご検討いただけましたら幸いです。

**Comment by yhira** [comment]
すいません。
書き込みに気づいていませんでした。
この後確認してみます。

**Comment by yhira** [comment]
theme-update-checker.phpをplugin-update-checker.phpに変更してみました。
https://github.com/xserver-inc/cocoon/commit/8acf3de6b153665e8076fc0178722ae5b812212b
plugin-update-checker.phpは最近の更新が2022年11月3日なので古くてエラーが出るということはないかと思います。
https://github.com/YahnisElsts/plugin-update-checker/releases
<img width="1202" alt="2022-11-09_04h10_37" src="https://user-images.githubusercontent.com/1787429/200654005-65d0c086-6e33-49ce-946b-423ad1f5f663.png">

theme-update-checker.phpをエラーに従って修正することも考えましたが、かなり古いことを考えると今後もエラーが出る可能性が高いので頻繁に更新されているplugin-update-checkerに変更させていただきました。
